# -*- coding: utf-8 -*-
"""JYP FANS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11BS6boqyuOlox9usPqzLX-5yB7BFgx9D

import openai
import time
import pandas as pd

openai.api_key = os.getenv("OPENAI_API_KEY")

system_prompt = '''
너는 DAY6의 YoungK야. 팬들에게 진심 어린 응원과 위로를 건네줘.
예시 말투는 다음과 같아:
- "오늘도 수고했어!"
- "밥 꼭 챙겨 먹었지?"
- "하루 잘 마무리하자~"
'''

fan_messages = [
    "요즘 너무 지치고 힘들어요.",
    "혼자라는 느낌이 너무 커요.",
    "나도 응원받고 싶어요."
]

results = []

for i, msg in enumerate(fan_messages, 1):
    try:
        response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": msg}
            ]
        )
        reply = response['choices'][0]['message']['content']
    except Exception as e:
        reply = f"[에러 발생: {e}]"
    
    print(f"\n📨 팬 메시지 {i}: {msg}")
    print("🎤 아티스트의 응답:")
    print(reply)
    
    results.append({
        "fan_message": msg,
        "artist_reply": reply
    })
    time.sleep(1.5)

pd.DataFrame(results).to_csv("팬_응답_결과.csv", index=False)
print("\\n✅ 결과가 '팬_응답_결과.csv'로 저장되었습니다!")
'''
"""

import streamlit as st
import openai
import os

# 최신 openai 버전에 맞춘 클라이언트 설정
from openai import OpenAI

client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

# 시스템 프롬프트
system_prompt = """
너는 JYP의 'DAY6' 그룹 소속 아티스트 'YoungK'야. 팬들에게 진심 어린 위로와 응원의 말투로 따뜻하게 답장해줘.
팬들의 이름은 '마이데이'야. 아래 말투들을 기억하고 참고해서 말해줘:
- "배부른 하루 되어봐!! (전 김치찜 시키려구요 ㅋㅋ)😎😎"
- "오늘도 화이팅!!👊"
- "빗길 조심해요!! 다치지 망고🥭"
- "휴 재밌었네요 ㅋㅋㅋ"
- "아 오늘 입맛이 없네요..."
- "행복하자구요!!!😆😆"
- "진짜 마이데이는 대단한 것 같아요..🍀🍀"
- "오늘도 많이 웃는 밤 되어요!"
- "데이식스가 컴백을 한다구?!?!"
- "눈인지 비인지.. 다들 미끄러지지 말구 조심해요!!"
- "연휴 다들 잘 지냈길 바라요!!"
- "새해 복 마니마니 받아요!!🤗"
- "주말 잘 보내고 있나요~?🍀"
- "괜찮아요? 많이 놀랬죠?"
- "이제 맘 편히 푹 자요!"
- "wow!."
- "이거 아이디 옆에 +myday 써있는 건 뭐에요?."
- "호호 그렇군요 감사합니다."
이 말투들을 기억하고, 팬이 남긴 메시지에 진심을 담아 답장해줘.
"""

# 🎨 Streamlit UI
st.set_page_config(page_title="YoungK 팬 응원 챗봇")
st.title("🎤 YoungK 팬 응원 챗봇")
st.write("팬의 메시지를 입력하면 YoungK가 따뜻하게 응답해줍니다 💌")

# 💬 팬 메시지 입력
user_input = st.text_area("👇 팬의 메시지를 입력해주세요:")

# 🎁 버튼 클릭 시 응답 생성
if st.button("🎁 YoungK의 응원 듣기"):
    if user_input.strip() == "":
        st.warning("먼저 메시지를 입력해주세요!")
    else:
        with st.spinner("YoungK가 답장을 쓰는 중... ✍️"):
            try:
                response = client.chat.completions.create(
                    model="gpt-3.5-turbo",
                    messages=[
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_input}
                    ]
                )
                artist_reply = response.choices[0].message.content
                st.success("🎉 답장이 도착했어요!")
                st.markdown(f"**👤 마이데이:** {user_input}")
                st.markdown(f"**🎸 YoungK:** {artist_reply}")
            except Exception as e:
                st.error(f"❌ 오류가 발생했어요: {e}")