# -*- coding: utf-8 -*-
"""JYP FANS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11BS6boqyuOlox9usPqzLX-5yB7BFgx9D

import openai
import time
import pandas as pd

openai.api_key = os.getenv("OPENAI_API_KEY")

system_prompt = '''
너는 DAY6의 YoungK야. 팬들에게 진심 어린 응원과 위로를 건네줘.
예시 말투는 다음과 같아:
- "오늘도 수고했어!"
- "밥 꼭 챙겨 먹었지?"
- "하루 잘 마무리하자~"
'''

fan_messages = [
    "요즘 너무 지치고 힘들어요.",
    "혼자라는 느낌이 너무 커요.",
    "나도 응원받고 싶어요."
]

results = []

for i, msg in enumerate(fan_messages, 1):
    try:
        response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": msg}
            ]
        )
        reply = response['choices'][0]['message']['content']
    except Exception as e:
        reply = f"[에러 발생: {e}]"
    
    print(f"\n📨 팬 메시지 {i}: {msg}")
    print("🎤 아티스트의 응답:")
    print(reply)
    
    results.append({
        "fan_message": msg,
        "artist_reply": reply
    })
    time.sleep(1.5)

pd.DataFrame(results).to_csv("팬_응답_결과.csv", index=False)
print("\\n✅ 결과가 '팬_응답_결과.csv'로 저장되었습니다!")
'''
"""

import streamlit as st
import openai
import os

# OpenAI API 키 설정 (Streamlit에서 Secrets 관리 권장)
openai.api_key = os.getenv("OPENAI_API_KEY")

# 시스템 프롬프트 설정
system_prompt = """
너는 JYP의 'DAY6' 그룹 소속 아티스트 'YoungK'야. 팬들에게 진심 어린 위로와 응원의 말투로 따뜻하게 답장해줘.
팬들의 이름은 '마이데이'야. 아래 말투들을 기억하고 참고해서 말해줘:
- "배부른 하루 되어봐!! (전 김치찜 시키려구요 ㅋㅋ)😎😎"
- "오늘도 화이팅!!👊"
- "빗길 조심해요!! 다치지 망고🥭"
- "휴 재밌었네요 ㅋㅋㅋ"
- "아 오늘 입맛이 없네요..."
- "행복하자구요!!!😆😆"
- "진짜 마이데이는 대단한 것 같아요..🍀🍀"
- "오늘도 많이 웃는 밤 되어요!"
- "데이식스가 컴백을 한다구?!?!"
- "눈인지 비인지.. 다들 미끄러지지 말구 조심해요!!"
- "연휴 다들 잘 지냈길 바라요!!"
- "새해 복 마니마니 받아요!!🤗"
- "주말 잘 보내고 있나요~?🍀"
- "괜찮아요? 많이 놀랬죠?"
- "이제 맘 편히 푹 자요!"
- "wow!."
- "이거 아이디 옆에 +myday 써있는 건 뭐에요?."
- "호호 그렇군요 감사합니다."
이 말투들을 기억하고, 팬이 남긴 메시지에 진심을 담아 답장해줘.
"""

# 팬 메시지 리스트
fan_messages = [
    "요즘 너무 지치고 힘들어요.",
    "아무도 나를 응원하지 않는 것 같아요.",
    "매일매일 울고 있어요. 위로가 필요해요.",
    "꿈을 포기하고 싶어요. 자신이 없어요.",
    "오늘 하루도 버티느라 너무 힘들었어요.",
    "누구에게도 털어놓을 수가 없어서 너무 외로워요.",
    "좋아하는 걸 계속해도 괜찮을지 모르겠어요.",
    "자신감이 점점 없어지는 것 같아요.",
    "지금의 나를 좋아해주는 사람이 있을까요?",
    "그냥 누가 '괜찮다'고 말해줬으면 좋겠어요.",
    "힘들다고 말하는 것도 지쳤어요.",
    "기댈 곳이 필요해요.",
    "그냥 안아주고 싶다는 말이 듣고 싶어요.",
    "열심히 해도 늘 부족한 기분이에요.",
    "저를 사랑해주는 사람이 없다고 느껴져요.",
    "아무 일도 하기 싫어요.",
    "계속 울게 되는 요즘이에요.",
    "왜 이렇게 외로울까요?",
    "모든 게 무기력해요.",
    "내가 뭘 잘하는 사람인지 모르겠어요.",
    "사소한 일에도 자꾸 눈물이 나요.",
    "힘내라는 말이 부담스럽게 느껴져요.",
    "매일이 너무 고통스러워요.",
    "행복이란 걸 잊어버린 것 같아요.",
    "무기력한 내 자신이 미워요.",
    "혼자라는 느낌이 너무 커요.",
    "사람들이 나를 싫어하는 것 같아요.",
    "내가 무슨 의미가 있을까 싶어요.",
    "버텨야 한다는 게 너무 괴로워요.",
    "나도 응원받고 싶어요.",
    "나를 믿어주는 사람 하나만 있으면 좋겠어요.",
    "그냥 사라지고 싶은 기분이에요.",
    "내 마음을 이해해주는 사람이 없어요.",
    "말 한마디라도 따뜻하게 해주는 사람이 필요해요.",
    "누구에게도 기대지 못하는 게 너무 외로워요.",
    "꿈이 있지만 다가가기 무서워요"
]

# Streamlit UI
st.set_page_config(page_title="YoungK 팬 응원 챗봇")
st.title("🎤 YoungK 팬 응원 챗봇")
st.write("팬의 메시지를 입력하면 YoungK가 따뜻하게 응답해줍니다 💌")

selected_message = st.selectbox("👇 팬 메시지를 선택해 주세요:", fan_messages)

if st.button("🎁 YoungK의 응원 듣기"):
    with st.spinner("YoungK가 답장을 쓰는 중... ✍️"):
        try:
            response = openai.ChatCompletion.create(
                model="gpt-3.5-turbo",
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": selected_message}
                ]
            )
            artist_reply = response['choices'][0]['message']['content']
            st.success("🎉 답장이 도착했어요!")
            st.markdown(f"**팬:** {selected_message}")
            st.markdown(f"**YoungK:** {artist_reply}")
        except Exception as e:
            st.error(f"오류가 발생했어요: {e}")