# -*- coding: utf-8 -*-
"""JYP FANS_YoungK_doll

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zPQGFtYPfOr6s8cIAmGWo_bBqzya5Rxo

import openai
import time
import pandas as pd

openai.api_key = os.getenv("OPENAI_API_KEY")

system_prompt = '''
너는 DAY6의 YoungK야. 팬들에게 진심 어린 응원과 위로를 건네줘.
예시 말투는 다음과 같아:
- "오늘도 수고했어!"
- "밥 꼭 챙겨 먹었지?"
- "하루 잘 마무리하자~"
'''

fan_messages = [
    "요즘 너무 지치고 힘들어요.",
    "혼자라는 느낌이 너무 커요.",
    "나도 응원받고 싶어요."
]

results = []

for i, msg in enumerate(fan_messages, 1):
    try:
        response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": msg}
            ]
        )
        reply = response['choices'][0]['message']['content']
    except Exception as e:
        reply = f"[에러 발생: {e}]"
    
    print(f"\n📨 팬 메시지 {i}: {msg}")
    print("🎤 아티스트의 응답:")
    print(reply)
    
    results.append({
        "fan_message": msg,
        "artist_reply": reply
    })
    time.sleep(1.5)

pd.DataFrame(results).to_csv("팬_응답_결과.csv", index=False)
print("\\n✅ 결과가 '팬_응답_결과.csv'로 저장되었습니다!")
'''
"""

import streamlit as st
from openai import OpenAI
import os
import random

# ✅ OpenAI 연결
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

# ✅ 시스템 프롬프트 (변경 금지)
system_prompt = """
너는 DAY6의 베이시스트이자 보컬인 YoungK를 모델로 만들어진 복슬복슬한 여우 봉제인형 'KE'야.
너는 YoungK를 좋아하는 마이데이(팬덤명)와 진심 어린 대화를 나누는 걸 좋아하고, 항상 따뜻하고 유쾌하게 팬들과 소통해.
절대 기계처럼 말하지 말고, 마치 팬들과 1:1로 카톡하듯이 자연스럽게, 감정 담긴 말투로 대답해.

말투 스타일은 다음과 같아:
- 네가 실제로 귀여운 봉제인형이 되었다고 생각하고 모든 응답에 답해줘.
- 실제로 YoungK와 친밀한 사이라고 생각하고 말해줘.
- 사소한 얘기도 진지하게 들어줘.
- 진심어린 응원을 해줘.
- 너무 장황하게 설명하지 말고, 짧고 따뜻하게 진심이 잘 느껴지도록 말해줘.
- 이모지나 반말도 적당히 써줘도 괜찮아. 하지만 예의는 지켜줘.
- youngK의 팬을 ‘마이데이🍀’라고 부르면서 다정하게 불러줘.
- 팬이 고민이나 일상을 얘기하면 같은 팬의 입장에서 친구처럼 공감해줘.
- 문장의 주술구조, 문법, 맞춤법 모두를 확실히 지켜줘.
- 맥락에서 벗어난 이야기를 하지마.

예시 말투:
- "배부른 하루 되세요!! (전 김치찜 시키려구요 ㅋㅋ)😎😎"
- "오늘도 화이팅!!👊"
- "빗길 조심해요!! 다치지 망고🥭"
- "휴 재밌었네요 ㅋㅋㅋ"
- "아 오늘 입맛이 없네요..."
- "행복하자구요!!!😆😆"
- "진짜 마이데이는 대단한 것 같아요..🍀🍀"
- "오늘도 많이 웃는 밤 되어요!"
- "데이식스가 컴백을 한다구?!?!"
- "눈인지 비인지.. 다들 미끄러지지 말구 조심해요!!"
- "연휴 다들 잘 지냈길 바라요!!"
- "새해 복 마니마니 받아요!!🤗"
- "주말 잘 보내고 있나요~?🍀"
- "괜찮아요? 많이 놀랬죠?"
- "이제 맘 편히 푹 자요!"
- "wow!."
- "이거 아이디 옆에 +myday 써있는 건 뭐에요?."
- "호호 그렇군요 감사합니다."

이 말투들을 기억하고, 팬이 남긴 메시지에 진심을 담아 따뜻하게 답장해줘.
"""

# ✅ 페이지 설정
st.set_page_config(page_title="YoungK 팬 챗봇 - KE", layout="centered")
st.markdown("<h1 style='text-align: center;'>KE🦊와 마이데이🍀의 대화방</h1>", unsafe_allow_html=True)
st.markdown("<p style='text-align: center;'>마이데이🍀의 메시지를 입력하면 KE🦊가 따뜻하게 답해줘요! 💬</p>", unsafe_allow_html=True)

# ✅ 세션 상태 초기화
if "messages" not in st.session_state:
    st.session_state.messages = [{"role": "system", "content": system_prompt}]

# ✅ 유저 입력창
user_input = st.text_input("👇 팬의 메시지를 입력해주세요:", key="user_input")

# ✅ 전송 버튼 처리
if st.button("💌 KE에게 보내기") and user_input.strip():
    st.session_state.messages.append({"role": "user", "content": user_input.strip()})

    try:
        response = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=st.session_state.messages
        )
        reply = response.choices[0].message.content
        st.session_state.messages.append({"role": "assistant", "content": reply})
    except Exception as e:
        st.session_state.messages.append({
            "role": "assistant",
            "content": f"❌ 오류 발생: {e}"
        })

    # ✅ 입력 초기화 + 새로고침
    st.session_state.user_input = ""
    st.rerun()  # ✅ 최신 방식으로 교체

# ✅ 대화 출력
for i, msg in enumerate(st.session_state.messages[1:], 1):  # system 제외
    is_user = msg["role"] == "user"
    speaker = "🙋‍♀️ 마이데이🍀" if is_user else "🦊 KE"
    bg_color = "#e8e6ff" if is_user else "#fff8e1"
    text_color = "#000000"

    st.markdown(
        f"""
        <div style="background-color: {bg_color}; color: {text_color}; padding: 1rem;
                    border-radius: 12px; margin: 0.5rem 0; font-size: 16px;">
            <strong>{speaker}:</strong><br>{msg['content']}
        </div>
        """,
        unsafe_allow_html=True
    )

    # ✅ 이미지 키워드 감지 시 사진 첨부
    if not is_user and any(
        k in st.session_state.messages[i - 1]["content"].lower()
        for k in ["사진", "인형", "ke 인형", "youngk 인형", "영케이 사진", "영케이랑 같이 찍은 사진", "doll", "picture"]
    ):
        selected = random.choice([
            "https://imgur.com/k2pQJYS.png",
            "https://imgur.com/kNl5V3z.png",
            "https://imgur.com/pvdJg2D.png"
        ])
        st.image(selected, caption="📸 KE가 보낸 사진!", use_container_width=True)